I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 113, in script call
    call level_up #NOTE: lvl up test
  File "game/script.rpy", line 1334, in script
    $ social_stats["Charisma"] = social_stats["vir"] + 1
  File "game/script.rpy", line 1334, in <module>
    $ social_stats["Charisma"] = social_stats["vir"] + 1
KeyError: u'vir'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 113, in script call
    call level_up #NOTE: lvl up test
  File "game/script.rpy", line 1334, in script
    $ social_stats["Charisma"] = social_stats["vir"] + 1
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 1334, in <module>
    $ social_stats["Charisma"] = social_stats["vir"] + 1
KeyError: u'vir'

Windows-7-6.1.7601-SP1
Ren'Py 7.4.11.2266
Hudokai The Visual Novel 1.0
Sat May 14 21:30:01 2022
